on: [push, pull_request]

name: Build LuaJIT

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          name: LuaJIT/LuaJIT
          ref: refs/tags/v2.1
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Compile LuaJIT
        run: |
          cd src
          ./msvcbuild.bat static
      - name: Archive built assets
        uses: actions/upload-artifact@v3
        with:
          name: src-with-compiled-binaries
          path: src