on: workflow_dispatch
# on: push

name: Build LuaJIT

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        command: [static, ""]
    steps:
      - uses: actions/checkout@v2
        with:
          repository: LuaJIT/LuaJIT
          ref: refs/heads/v2.1
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Compile LuaJIT
        run: |
          cd src
          ./msvcbuild.bat ${{ matrix.command }}
      - name: Archive built assets
        uses: actions/upload-artifact@v3
        with:
          name: src-with-compiled-binaries
          path: src